"""Pydantic v2 models for the KhaiNet pipeline.

These models represent the data structures used within the pipeline:
Kafka messages, sensor events, detection results, tuning labels, and
pipeline statistics.

Conventions (same as detection/ and tuning/):
- ``from __future__ import annotations``
- ``ConfigDict(extra="ignore")``
- Timestamps accept datetime, ISO-8601 string, or epoch float
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator


def _parse_timestamp(v: Any) -> datetime:
    """Accept datetime, ISO-8601 string (with or without 'Z'), or epoch float."""
    if isinstance(v, datetime):
        return v if v.tzinfo else v.replace(tzinfo=timezone.utc)
    if isinstance(v, str):
        v = v.replace("Z", "+00:00")
        return datetime.fromisoformat(v)
    if isinstance(v, (int, float)):
        return datetime.fromtimestamp(v, tz=timezone.utc)
    raise ValueError(f"Invalid timestamp: {v}")


class KafkaMessage(BaseModel):
    """Generic wrapper for a Kafka message.

    Attributes:
        topic: Kafka topic the message was sent to / received from.
        timestamp: Message timestamp (Kafka timestamp or event time).
        payload: The message payload as a dictionary.
        headers: Optional Kafka headers (key-value pairs).
        key: Optional partition key.
        partition: Kafka partition number.
        offset: Kafka offset.
    """

    model_config = ConfigDict(extra="ignore")

    topic: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict[str, Any] = Field(default_factory=dict)
    headers: dict[str, str] = Field(default_factory=dict)
    key: str | None = None
    partition: int | None = None
    offset: int | None = None

    @field_validator("timestamp", mode="before")
    @classmethod
    def parse_timestamp(cls, v: Any) -> datetime:
        return _parse_timestamp(v)

    @property
    def ts_epoch(self) -> float:
        """Epoch seconds for fast temporal comparison."""
        return self.timestamp.timestamp()


class PipelineStats(BaseModel):
    """Runtime statistics for the pipeline.

    Attributes:
        events_produced: Total events produced to Kafka.
        events_consumed: Total events consumed from Kafka.
        anomalies_detected: Total anomalies flagged by detection.
        labels_generated: Total labels generated by tuning.
        active_learning_queries: Total active learning queries issued.
        uptime_seconds: Pipeline uptime in seconds.
    """

    model_config = ConfigDict(extra="ignore")

    events_produced: int = 0
    events_consumed: int = 0
    anomalies_detected: int = 0
    labels_generated: int = 0
    active_learning_queries: int = 0
    uptime_seconds: float = 0.0


class SensorEvent(BaseModel):
    """A normalized event from the sensor simulator.

    Attributes:
        event_type: Type of event (zeek_conn, zeek_dns, zeek_http, zeek_ssl,
            suricata_alert, wazuh_event).
        source: Source sensor (zeek, suricata, wazuh).
        data: The event payload as a dictionary (model_dump of the Pydantic model).
        timestamp: Event timestamp.
        is_anomaly: Whether this event is an injected anomaly.
        anomaly_type: Type of anomaly if is_anomaly is True.
    """

    model_config = ConfigDict(extra="ignore")

    event_type: str
    source: str  # zeek, suricata, wazuh
    data: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_anomaly: bool = False
    anomaly_type: str | None = None

    @field_validator("timestamp", mode="before")
    @classmethod
    def parse_timestamp(cls, v: Any) -> datetime:
        return _parse_timestamp(v)

    @property
    def ts_epoch(self) -> float:
        return self.timestamp.timestamp()


class DetectionResult(BaseModel):
    """Result of the detection consumer processing a batch of events.

    Attributes:
        event_id: Unique identifier for this detection result.
        model_scores: Dict mapping model name → score (0-1).
        fused_score: Combined/fused anomaly score (0-1).
        is_anomaly: Whether the fused score exceeds the threshold.
        threshold: Decision threshold used.
        timestamp: When the detection was performed.
        src_ip: Source IP (pseudonymized hash).
        dst_ip: Destination IP (pseudonymized hash).
        details: Additional details from the detection models.
    """

    model_config = ConfigDict(extra="ignore")

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    model_scores: dict[str, float] = Field(default_factory=dict)
    fused_score: float = Field(default=0.0, ge=0.0, le=1.0)
    is_anomaly: bool = False
    threshold: float = 0.5
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    src_ip: str = ""
    dst_ip: str = ""
    details: dict[str, Any] = Field(default_factory=dict)

    @field_validator("timestamp", mode="before")
    @classmethod
    def parse_timestamp(cls, v: Any) -> datetime:
        return _parse_timestamp(v)

    @field_validator("fused_score", mode="before")
    @classmethod
    def clamp_score(cls, v: Any) -> float:
        v = float(v)
        return max(0.0, min(1.0, v))

    @property
    def ts_epoch(self) -> float:
        return self.timestamp.timestamp()


class TuningLabel(BaseModel):
    """A label generated by the tuning consumer.

    Attributes:
        event_id: The event this label applies to.
        source: Label source (suricata, wazuh, misp, brain, analyst, weak_supervision).
        label: True=anomaly, False=normal.
        confidence: Confidence score (0-1).
        timestamp: When the label was generated.
        mitre_attack_id: Optional MITRE ATT&CK technique ID.
        event_type: Optional event type classification.
    """

    model_config = ConfigDict(extra="ignore")

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    source: str
    label: bool
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    mitre_attack_id: str | None = None
    event_type: str | None = None

    @field_validator("timestamp", mode="before")
    @classmethod
    def parse_timestamp(cls, v: Any) -> datetime:
        return _parse_timestamp(v)

    @property
    def ts_epoch(self) -> float:
        return self.timestamp.timestamp()
